language: rust
rust:
  - nightly
env:
  - DOCS_DEFAULT_MODULE=mioco
script:
  - cargo build
  - cargo build --example echo
  - cargo test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ec2440f26c71d930f26c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
