[package]
name = "mioco"
version = "0.0.3"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[lib]
name = "mioco"
path = "src/lib.rs"

[dependencies]
nix = "*"
coroutine = "*"

[dependencies.mio]
git = "https://github.com/carllerche/mio"
