[package]
name = "mioco"
version = "0.0.1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]

[lib]
name = "mioco"
path = "src/lib.rs"

[dependencies]
nix = "*"
coroutine = "*"

[dependencies.mio]
git = "https://github.com/carllerche/mio"